GET /api/2.3/tenders/5be924af98a445448a0a8a81b5f109db/bids/0e394c14e7d6442a8e054b41ace2b246?acc_token=409eda271d244a6a93f9e9b2013eba36 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "0e394c14e7d6442a8e054b41ace2b246"
  }
}

