PATCH /api/2.3/tenders/92273add0c664e1ca95782f88c4ad99f/bids/57ba5ce7bfe143a98d40bf5e8ab07b4e?acc_token=db0040a4beb94770880c5e44b1b66baa HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 124
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "759fad6c111e4cb9a20d5c0466beabc6", 
        "value": {
          "amount": 500
        }
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "date": "2017-02-16T11:57:16.896063+02:00", 
    "status": "pending", 
    "id": "57ba5ce7bfe143a98d40bf5e8ab07b4e", 
    "lotValues": [
      {
        "relatedLot": "759fad6c111e4cb9a20d5c0466beabc6", 
        "date": "2017-02-16T11:57:16.896721+02:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

