PATCH /api/2.3/tenders/5be924af98a445448a0a8a81b5f109db/bids/0e394c14e7d6442a8e054b41ace2b246?acc_token=409eda271d244a6a93f9e9b2013eba36 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 124
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "f2542173d5f74511bd1d3fd7b0ca6333", 
        "value": {
          "amount": 500
        }
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "date": "2017-02-16T13:35:38.793024+02:00", 
    "status": "pending", 
    "id": "0e394c14e7d6442a8e054b41ace2b246", 
    "lotValues": [
      {
        "relatedLot": "f2542173d5f74511bd1d3fd7b0ca6333", 
        "date": "2017-02-16T13:35:38.793713+02:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}

