GET /api/2.3/tenders/92273add0c664e1ca95782f88c4ad99f/bids/d347b6ed9ea74523ac348408c942320f?acc_token=b612faf798df458aa4fe53bc2e77cc88 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "invalid", 
    "id": "d347b6ed9ea74523ac348408c942320f"
  }
}

