POST /api/2.3/tenders/5be924af98a445448a0a8a81b5f109db/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 849
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "lotValues": [
      {
        "relatedLot": "f2542173d5f74511bd1d3fd7b0ca6333", 
        "value": {
          "amount": 500
        }
      }, 
      {
        "relatedLot": "37dbcb6cabfe4c44b6c42457cb39dcc9", 
        "value": {
          "amount": 500
        }
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк", 
          "email": "aagt@gmail.com"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79013", 
          "region": "м. Львів", 
          "streetAddress": "вул. Островського, 34", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/5be924af98a445448a0a8a81b5f109db/bids/c8e665a8d0f8479f82d29057e9a1eba8
{
  "access": {
    "transfer": "997250d856de455a8f2e6b7ba0a0712c", 
    "token": "0173b76dcf374ed1bcfe585440525a67"
  }, 
  "data": {
    "date": "2017-02-16T13:35:38.907221+02:00", 
    "status": "pending", 
    "id": "c8e665a8d0f8479f82d29057e9a1eba8", 
    "lotValues": [
      {
        "relatedLot": "f2542173d5f74511bd1d3fd7b0ca6333", 
        "date": "2017-02-16T13:35:38.907907+02:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }, 
      {
        "relatedLot": "37dbcb6cabfe4c44b6c42457cb39dcc9", 
        "date": "2017-02-16T13:35:38.908518+02:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ]
  }
}

