PATCH /api/2.3/tenders/92273add0c664e1ca95782f88c4ad99f/bids/d347b6ed9ea74523ac348408c942320f?acc_token=b612faf798df458aa4fe53bc2e77cc88 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 124
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "pending", 
    "lotValues": [
      {
        "relatedLot": "759fad6c111e4cb9a20d5c0466beabc6", 
        "value": {
          "amount": 500
        }
      }
    ]
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "date": "2017-02-16T11:57:16.795971+02:00", 
    "status": "pending", 
    "id": "d347b6ed9ea74523ac348408c942320f", 
    "lotValues": [
      {
        "relatedLot": "759fad6c111e4cb9a20d5c0466beabc6", 
        "date": "2017-02-16T11:57:16.796657+02:00", 
        "status": "pending", 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ]
  }
}

