PATCH /api/2.3/tenders/92273add0c664e1ca95782f88c4ad99f?acc_token=ab9ee30503a846b0a8dc2e4639070f8e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification.stand-still", 
    "complaintPeriod": {
      "startDate": "2017-02-11T11:57:17.355951+02:00", 
      "endDate": "2017-02-11T11:57:18.355951+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-02-11T11:57:17.355951+02:00", 
      "clarificationsUntil": "2017-02-15T11:57:17.355951+02:00", 
      "endDate": "2017-02-15T11:57:17.355951+02:00", 
      "invalidationDate": "2017-02-16T11:57:17.005406+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "operator": "ua", 
    "next_check": "2017-02-17T00:00:01+02:00", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "92273add0c664e1ca95782f88c4ad99f", 
    "transfer_token": "9f1674e2f20933c8deda0e64541815434704f5723debcfddc5548a5590922d12be466810cfcf5e61bcbfcaf3e374e9e95508c102432dc61cba38387988b680b4", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "auctionPeriod": {
          "shouldStartAfter": "2017-02-18T00:00:00+02:00"
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2017-02-16T11:57:16.399527+02:00", 
        "id": "759fad6c111e4cb9a20d5c0466beabc6"
      }, 
      {
        "status": "unsuccessful", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2017-02-16T11:57:17.538946+02:00", 
        "id": "f3cfaf91e5274d84af8db37f66e85144"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2017-02-16T11:57:17.530021+02:00", 
      "endDate": "2017-02-17T00:00:01+02:00"
    }, 
    "tenderID": "R-UA-2017-02-16-000001", 
    "dateModified": "2017-02-16T11:57:18.105403+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2017-02-11T11:57:17.355951+02:00", 
      "endDate": "2017-02-16T11:57:17.355951+02:00"
    }, 
    "procurementMethodType": "aboveThresholdTS", 
    "qualifications": [
      {
        "status": "active", 
        "date": "2017-02-16T11:57:17.748406+02:00", 
        "lotID": "759fad6c111e4cb9a20d5c0466beabc6", 
        "id": "2e118b4f6d6145c6bef3a902b546e82e", 
        "bidID": "d347b6ed9ea74523ac348408c942320f"
      }, 
      {
        "status": "active", 
        "date": "2017-02-16T11:57:17.863318+02:00", 
        "lotID": "759fad6c111e4cb9a20d5c0466beabc6", 
        "id": "03b664d0037e48b5a562d2a07ecc7ef3", 
        "bidID": "57ba5ce7bfe143a98d40bf5e8ab07b4e"
      }
    ], 
    "date": "2017-02-16T11:57:18.105403+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "759fad6c111e4cb9a20d5c0466beabc6", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-08T11:57:03.681359+02:00", 
          "endDate": "2017-04-07T11:57:03.681416+02:00"
        }, 
        "id": "c41902c427ea478a966b00e7ac478f0b", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "relatedLot": "f3cfaf91e5274d84af8db37f66e85144", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-08T11:57:03.681447+02:00", 
          "endDate": "2017-04-07T11:57:03.681470+02:00"
        }, 
        "id": "6547a329f0504a3f969a64e6b1f40e05", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "id": "d347b6ed9ea74523ac348408c942320f", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "57ba5ce7bfe143a98d40bf5e8ab07b4e", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

