POST /api/2.3/tenders/92273add0c664e1ca95782f88c4ad99f/lots?acc_token=ab9ee30503a846b0a8dc2e4639070f8e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 214
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "description": "Опис Лот №1", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "title": "Лот №1"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/92273add0c664e1ca95782f88c4ad99f/lots/759fad6c111e4cb9a20d5c0466beabc6
{
  "data": {
    "status": "active", 
    "description": "Опис Лот №1", 
    "title": "Лот №1", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-03-21T00:00:00+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-02-16T11:57:16.399527+02:00", 
    "id": "759fad6c111e4cb9a20d5c0466beabc6"
  }
}

