GET /api/2.3/tenders/5be924af98a445448a0a8a81b5f109db?acc_token=3254958c3d944d8eb0f670a2d9af96d5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification", 
    "complaintPeriod": {
      "startDate": "2017-02-11T13:35:39.377098+02:00", 
      "endDate": "2017-02-11T13:35:40.377098+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-02-11T13:35:39.377098+02:00", 
      "clarificationsUntil": "2017-02-15T13:35:39.377098+02:00", 
      "endDate": "2017-02-15T13:35:39.377098+02:00", 
      "invalidationDate": "2017-02-16T13:35:39.023355+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "operator": "ua", 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }, 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "5be924af98a445448a0a8a81b5f109db", 
    "transfer_token": "68b667da50b941a3363a9557b4eb10b3a52e735651e3574d0fe3c6c29a68547e3fa95cfe5bf13db0148eae35a204b9cdad3fc2d4a7601795a13d3faadd071872", 
    "title": "Послуги шкільних їдалень", 
    "lots": [
      {
        "status": "active", 
        "description": "Опис Лот №1", 
        "title": "Лот №1", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 500.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2017-02-16T13:35:38.383146+02:00", 
        "id": "f2542173d5f74511bd1d3fd7b0ca6333"
      }, 
      {
        "status": "unsuccessful", 
        "description": "Опис Лот №2", 
        "title": "Лот №2", 
        "minimalStep": {
          "currency": "UAH", 
          "amount": 35.0, 
          "valueAddedTaxIncluded": true
        }, 
        "value": {
          "currency": "UAH", 
          "amount": 400.0, 
          "valueAddedTaxIncluded": true
        }, 
        "date": "2017-02-16T13:35:39.560544+02:00", 
        "id": "37dbcb6cabfe4c44b6c42457cb39dcc9"
      }
    ], 
    "qualificationPeriod": {
      "startDate": "2017-02-16T13:35:39.551420+02:00"
    }, 
    "tenderID": "R-UA-2017-02-16-000001", 
    "dateModified": "2017-02-16T13:35:39.560544+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2017-02-11T13:35:39.377098+02:00", 
      "endDate": "2017-02-16T13:35:39.377098+02:00"
    }, 
    "procurementMethodType": "aboveThresholdTS", 
    "qualifications": [
      {
        "status": "pending", 
        "date": "2017-02-16T13:35:39.552505+02:00", 
        "lotID": "f2542173d5f74511bd1d3fd7b0ca6333", 
        "id": "a364da935c8d4be1ae0f6daf125a4893", 
        "bidID": "0e394c14e7d6442a8e054b41ace2b246"
      }, 
      {
        "status": "pending", 
        "date": "2017-02-16T13:35:39.552853+02:00", 
        "lotID": "f2542173d5f74511bd1d3fd7b0ca6333", 
        "id": "b8f81df67c624be983e2bb55e36afe14", 
        "bidID": "c8e665a8d0f8479f82d29057e9a1eba8"
      }
    ], 
    "date": "2017-02-16T13:35:39.560544+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "relatedLot": "f2542173d5f74511bd1d3fd7b0ca6333", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-08T13:35:25.283623+02:00", 
          "endDate": "2017-04-07T13:35:25.283712+02:00"
        }, 
        "id": "0322a1ec11a9443daf7e03d1dc070caf", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "relatedLot": "37dbcb6cabfe4c44b6c42457cb39dcc9", 
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-08T13:35:25.283746+02:00", 
          "endDate": "2017-04-07T13:35:25.283773+02:00"
        }, 
        "id": "bacc2842f1ba4337ae7b0840ab0f1c0c", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "pending", 
        "id": "0e394c14e7d6442a8e054b41ace2b246", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "pending", 
        "id": "c8e665a8d0f8479f82d29057e9a1eba8", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 900.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "lowestCost"
  }
}

