PATCH /api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/questions/9f81c4879d5748c7a601deb37ed57627?acc_token=12edb463846948e88706a2df2912ba45 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "dateAnswered": "2017-02-16T13:35:28.749826+02:00", 
    "title": "Калорійність", 
    "date": "2017-02-16T13:35:28.651782+02:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "9f81c4879d5748c7a601deb37ed57627", 
    "questionOf": "tender"
  }
}

