PATCH /api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/qualifications/32cf035dd8ca41b2993e7813bc3939ad?acc_token=12edb463846948e88706a2df2912ba45 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "date": "2017-02-16T13:35:31.695774+02:00", 
    "id": "32cf035dd8ca41b2993e7813bc3939ad", 
    "bidID": "35e7d4ecdfe2489989257ea9acd43787"
  }
}

