GET /api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.auction", 
    "complaintPeriod": {
      "startDate": "2017-02-10T11:57:02.654559+02:00", 
      "endDate": "2017-02-10T11:57:03.654559+02:00"
    }, 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/tenders/5850b6f8866b495ab93c01287a832c5d", 
    "enquiryPeriod": {
      "startDate": "2017-02-10T11:57:02.654559+02:00", 
      "clarificationsUntil": "2017-02-15T11:57:02.654559+02:00", 
      "endDate": "2017-02-15T11:57:02.654559+02:00", 
      "invalidationDate": "2017-02-16T11:57:08.698230+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "operator": "ua", 
    "next_check": "2017-02-16T12:33:03.654559+02:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2017-02-16T11:57:07.086012+02:00", 
        "title": "Калорійність", 
        "date": "2017-02-16T11:57:06.997018+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "81765ea5329145e793ed2baaddbbdbc6", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "5850b6f8866b495ab93c01287a832c5d", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/documents/4d770985b7a841dbb172a79431f88157?download=1274c7f2e36449e9867140b0baf8f3d9", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T11:57:06.668408+02:00", 
        "id": "4d770985b7a841dbb172a79431f88157", 
        "dateModified": "2017-02-16T11:57:06.668444+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/documents/313b15e0c904489e9868c0db73eed310?download=f196407d7fbc4391a2e820cd8f5c30d4", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T11:57:06.773953+02:00", 
        "id": "313b15e0c904489e9868c0db73eed310", 
        "dateModified": "2017-02-16T11:57:06.773986+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/documents/313b15e0c904489e9868c0db73eed310?download=01e68f1be3fc471ba94405a6540111aa", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T11:57:06.773953+02:00", 
        "id": "313b15e0c904489e9868c0db73eed310", 
        "dateModified": "2017-02-16T11:57:06.886734+02:00"
      }
    ], 
    "transfer_token": "9cfbc8ee42081a203c705336c48d9fbbc1e9cebb4567f10f6debb8d419304caf82c53e0b9a063ec6b4dfac50136910fc52d6f4c5f4e086bc128626e235ec4701", 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2017-02-16T11:57:02.654559+02:00", 
      "endDate": "2017-02-16T11:57:03.654559+02:00"
    }, 
    "tenderID": "R-UA-2017-02-16-000001", 
    "auctionPeriod": {
      "startDate": "2017-02-16T11:57:03.654559+02:00", 
      "shouldStartAfter": "2017-02-17T00:00:00+02:00"
    }, 
    "dateModified": "2017-02-16T11:57:11.019586+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2017-02-10T11:57:02.654559+02:00", 
      "endDate": "2017-02-16T11:57:02.654559+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "date": "2017-02-16T11:57:09.805068+02:00", 
        "id": "a87379b8f25048d4a43e0e647f41dc75", 
        "bidID": "018a3958273a439ba83f5c996cb9525c"
      }, 
      {
        "status": "active", 
        "date": "2017-02-16T11:57:09.957494+02:00", 
        "id": "466650270fcf4832ab627ebe37717a58", 
        "bidID": "f312a5e0d7824a9782aa853d39357fa5"
      }, 
      {
        "status": "unsuccessful", 
        "date": "2017-02-16T11:57:10.112655+02:00", 
        "id": "8015a4384ef746b2b60bd6340008ce10", 
        "bidID": "d7ea82f49c684739b0503f593cd4d21d"
      }
    ], 
    "procurementMethodType": "aboveThresholdTS", 
    "date": "2017-02-16T11:57:10.572592+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-08T11:57:03.681359+02:00", 
          "endDate": "2017-04-07T11:57:03.681416+02:00"
        }, 
        "id": "b681beba402b4c5e9cf13db2dec1b70e", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-08T11:57:03.681447+02:00", 
          "endDate": "2017-04-07T11:57:03.681470+02:00"
        }, 
        "id": "5f47716322524940920f071a1df7a2f1", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/bids/018a3958273a439ba83f5c996cb9525c/documents/2a545ab3d99b40c3ac4f2b5eb16e3eff?download=917e8726d4f941bb9eccc8ce32f2b469", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-02-16T11:57:07.873882+02:00", 
            "id": "2a545ab3d99b40c3ac4f2b5eb16e3eff", 
            "dateModified": "2017-02-16T11:57:07.873914+02:00"
          }, 
          {
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "title": "Proposal_top_secrets.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/bids/018a3958273a439ba83f5c996cb9525c/documents/163b0fbd8cf04677a1e86fd53b14dcb9?download=82ce90cfe71d4579851dbdfb1500f521", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-02-16T11:57:08.000731+02:00", 
            "id": "163b0fbd8cf04677a1e86fd53b14dcb9", 
            "dateModified": "2017-02-16T11:57:08.000764+02:00"
          }
        ], 
        "id": "018a3958273a439ba83f5c996cb9525c", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "f312a5e0d7824a9782aa853d39357fa5", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "unsuccessful", 
        "id": "d7ea82f49c684739b0503f593cd4d21d", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

