GET /api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids/35e7d4ecdfe2489989257ea9acd43787?acc_token=1509d32e49c14586b7c50d272e9ff1f5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "date": "2017-02-16T13:35:30.730403+02:00", 
    "id": "35e7d4ecdfe2489989257ea9acd43787", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/69620e7245b048d696d61d9b5061cee2?key_for_bid=35e7d4ecdfe2489989257ea9acd43787"
  }
}

