GET /api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids/64c6b855beba4212a4e8434cec225ff3?acc_token=293f6dd5c1d94f3eafaa4320ed3a5494 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "Proposal.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids/64c6b855beba4212a4e8434cec225ff3/documents/d647bef6eee54a75adfaf07f87b7fbb1?download=9d8c61714bf04567849c2ca561ee1f0a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T13:35:29.551953+02:00", 
        "id": "d647bef6eee54a75adfaf07f87b7fbb1", 
        "dateModified": "2017-02-16T13:35:29.551986+02:00"
      }, 
      {
        "confidentiality": "buyerOnly", 
        "language": "uk", 
        "title": "Proposal_top_secrets.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids/64c6b855beba4212a4e8434cec225ff3/documents/6a9751a40b364da4aab33472bfc110cd?download=01fc3d85ef00483aa62bba9d86ce8dc9", 
        "confidentialityRationale": "Only our company sells badgers with pink hair.", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T13:35:29.672007+02:00", 
        "id": "6a9751a40b364da4aab33472bfc110cd", 
        "dateModified": "2017-02-16T13:35:29.672039+02:00"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "financialDocuments": [
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids/64c6b855beba4212a4e8434cec225ff3/financial_documents/4bfbbf9721df4b6ebecb3ae13b7bac65?download=4f265373001540be9433effcd0bb50ce", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T13:35:29.921324+02:00", 
        "id": "4bfbbf9721df4b6ebecb3ae13b7bac65", 
        "dateModified": "2017-02-16T13:35:29.921356+02:00"
      }, 
      {
        "confidentiality": "public", 
        "language": "uk", 
        "title": "financial_doc2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids/64c6b855beba4212a4e8434cec225ff3/financial_documents/ef1c6646564c4fdd98c141780f3f321a?download=36372a4dd51d441396acb0725da09e9a", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T13:35:30.058707+02:00", 
        "id": "ef1c6646564c4fdd98c141780f3f321a", 
        "dateModified": "2017-02-16T13:35:30.058747+02:00"
      }
    ], 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "date": "2017-02-16T13:35:29.316768+02:00", 
    "id": "64c6b855beba4212a4e8434cec225ff3", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/tenders/69620e7245b048d696d61d9b5061cee2?key_for_bid=64c6b855beba4212a4e8434cec225ff3"
  }
}

