PATCH /api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/awards/229e967569764592ac2256ac8b387299?acc_token=793615b998564fec946a60f44061b53b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2017-02-16T11:57:11.568329+02:00", 
      "endDate": "2017-02-16T11:57:15.568329+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "bid_id": "f312a5e0d7824a9782aa853d39357fa5", 
    "value": {
      "currency": "UAH", 
      "amount": 499.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-02-16T11:57:11.837808+02:00", 
    "id": "229e967569764592ac2256ac8b387299"
  }
}

