PATCH /api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids/64c6b855beba4212a4e8434cec225ff3/documents/6a9751a40b364da4aab33472bfc110cd?acc_token=293f6dd5c1d94f3eafaa4320ed3a5494 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "confidentiality": "buyerOnly"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "confidentiality": "buyerOnly", 
    "language": "uk", 
    "title": "Proposal_top_secrets.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids/64c6b855beba4212a4e8434cec225ff3/documents/6a9751a40b364da4aab33472bfc110cd?download=01fc3d85ef00483aa62bba9d86ce8dc9", 
    "confidentialityRationale": "Only our company sells badgers with pink hair.", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-02-16T13:35:29.672007+02:00", 
    "id": "6a9751a40b364da4aab33472bfc110cd", 
    "dateModified": "2017-02-16T13:35:29.672039+02:00"
  }
}

