PATCH /api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/cancellations/9290af2ff14641cbbd27daab24c4ce5b/documents/3b8ec254e1754cffbcff1d4db77a2f2f?acc_token=793615b998564fec946a60f44061b53b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 48
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "description": "Changed description"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "description": "Changed description", 
    "language": "uk", 
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/cancellations/9290af2ff14641cbbd27daab24c4ce5b/documents/3b8ec254e1754cffbcff1d4db77a2f2f?download=cb3504c770ce4148a292eb513aa40ae3", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-02-16T11:57:14.391065+02:00", 
    "id": "3b8ec254e1754cffbcff1d4db77a2f2f", 
    "dateModified": "2017-02-16T11:57:14.391103+02:00"
  }
}

