PATCH /api/2.3/tenders/69620e7245b048d696d61d9b5061cee2?acc_token=12edb463846948e88706a2df2912ba45 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 60
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "active.pre-qualification.stand-still"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "status": "active.pre-qualification.stand-still", 
    "complaintPeriod": {
      "startDate": "2017-02-10T13:35:25.282008+02:00", 
      "endDate": "2017-02-10T13:35:26.282008+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-02-10T13:35:25.282008+02:00", 
      "clarificationsUntil": "2017-02-15T13:35:25.282008+02:00", 
      "endDate": "2017-02-15T13:35:25.282008+02:00", 
      "invalidationDate": "2017-02-16T13:35:30.385476+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "operator": "ua", 
    "next_check": "2017-02-17T00:00:01+02:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "author": {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
            "id": "00137226", 
            "uri": "http://sch10.edu.vn.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }, 
        "title": "Калорійність", 
        "date": "2017-02-16T13:35:28.651782+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "dateAnswered": "2017-02-16T13:35:28.749826+02:00", 
        "id": "9f81c4879d5748c7a601deb37ed57627", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "69620e7245b048d696d61d9b5061cee2", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/documents/6f7cd941e6d64479a88f1404aeb178fb?download=e62c67795ed640ff83fb024d688fca9b", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T13:35:28.315761+02:00", 
        "id": "6f7cd941e6d64479a88f1404aeb178fb", 
        "dateModified": "2017-02-16T13:35:28.315794+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/documents/98f7c328d6c248528f1307046045127a?download=edd57144ff0c426fb38be60f4bb626d8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T13:35:28.425081+02:00", 
        "id": "98f7c328d6c248528f1307046045127a", 
        "dateModified": "2017-02-16T13:35:28.425114+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/documents/98f7c328d6c248528f1307046045127a?download=e870c5ad71704344ac8888d1090bedc5", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T13:35:28.425081+02:00", 
        "id": "98f7c328d6c248528f1307046045127a", 
        "dateModified": "2017-02-16T13:35:28.541864+02:00"
      }
    ], 
    "transfer_token": "9de1e547abcf27c2f7d08a8195ad010b5df63d057f3fd5edad2f951d40f33d060bed3c77d62ccedda2439665cd1d7a2b46a33f0e9c6d5295d691f598f6041d3d", 
    "title": "Послуги шкільних їдалень", 
    "qualificationPeriod": {
      "startDate": "2017-02-16T13:35:31.289640+02:00", 
      "endDate": "2017-02-17T00:00:01+02:00"
    }, 
    "tenderID": "R-UA-2017-02-16-000001", 
    "dateModified": "2017-02-16T13:35:32.315922+02:00", 
    "numberOfBids": 2, 
    "tenderPeriod": {
      "startDate": "2017-02-10T13:35:25.282008+02:00", 
      "endDate": "2017-02-16T13:35:25.282008+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-02-18T00:00:00+02:00"
    }, 
    "qualifications": [
      {
        "status": "active", 
        "date": "2017-02-16T13:35:31.534466+02:00", 
        "id": "5aaf7966f70e44a08abcec2a899a1745", 
        "bidID": "64c6b855beba4212a4e8434cec225ff3"
      }, 
      {
        "status": "active", 
        "date": "2017-02-16T13:35:31.695774+02:00", 
        "id": "32cf035dd8ca41b2993e7813bc3939ad", 
        "bidID": "35e7d4ecdfe2489989257ea9acd43787"
      }, 
      {
        "status": "unsuccessful", 
        "date": "2017-02-16T13:35:31.857840+02:00", 
        "id": "b7c47c7e87554904824e1868c75fdb1a", 
        "bidID": "631df1f78a114db8afb0c09592b20178"
      }
    ], 
    "date": "2017-02-16T13:35:32.315922+02:00", 
    "procurementMethodType": "aboveThresholdTS", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-08T13:35:25.283623+02:00", 
          "endDate": "2017-04-07T13:35:25.283712+02:00"
        }, 
        "id": "7a806448d0014f8fab19eaf6b328dfeb", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-08T13:35:25.283746+02:00", 
          "endDate": "2017-04-07T13:35:25.283773+02:00"
        }, 
        "id": "9462dda6089446b3b7aa7cda61518b33", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "bids": [
      {
        "status": "active", 
        "documents": [
          {
            "confidentiality": "public", 
            "language": "uk", 
            "title": "Proposal.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids/64c6b855beba4212a4e8434cec225ff3/documents/d647bef6eee54a75adfaf07f87b7fbb1?download=9d8c61714bf04567849c2ca561ee1f0a", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-02-16T13:35:29.551953+02:00", 
            "id": "d647bef6eee54a75adfaf07f87b7fbb1", 
            "dateModified": "2017-02-16T13:35:29.551986+02:00"
          }, 
          {
            "confidentiality": "buyerOnly", 
            "language": "uk", 
            "title": "Proposal_top_secrets.pdf", 
            "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids/64c6b855beba4212a4e8434cec225ff3/documents/6a9751a40b364da4aab33472bfc110cd?download=01fc3d85ef00483aa62bba9d86ce8dc9", 
            "confidentialityRationale": "Only our company sells badgers with pink hair.", 
            "format": "application/pdf", 
            "documentOf": "tender", 
            "datePublished": "2017-02-16T13:35:29.672007+02:00", 
            "id": "6a9751a40b364da4aab33472bfc110cd", 
            "dateModified": "2017-02-16T13:35:29.672039+02:00"
          }
        ], 
        "id": "64c6b855beba4212a4e8434cec225ff3", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "soleksuk@gmail.com", 
              "telephone": "+380 (432) 21-69-30", 
              "name": "Сергій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137256", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Школяр»", 
            "address": {
              "postalCode": "21100", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 33", 
              "region": "м. Вінниця", 
              "locality": "м. Вінниця"
            }
          }
        ]
      }, 
      {
        "status": "active", 
        "id": "35e7d4ecdfe2489989257ea9acd43787", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "aagt@gmail.com", 
              "telephone": "+380 (322) 91-69-30", 
              "name": "Андрій Олексюк"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "ДКП «Книга»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 34", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }, 
      {
        "status": "unsuccessful", 
        "id": "631df1f78a114db8afb0c09592b20178", 
        "tenderers": [
          {
            "contactPoint": {
              "email": "fake@mail.com", 
              "telephone": "+380 (322) 12-34-56", 
              "name": "Іван Іваненко"
            }, 
            "identifier": {
              "scheme": "UA-EDR", 
              "id": "00137226", 
              "uri": "http://www.sc.gov.ua/"
            }, 
            "name": "«Снігур»", 
            "address": {
              "postalCode": "79013", 
              "countryName": "Україна", 
              "streetAddress": "вул. Островського, 35", 
              "region": "м. Львів", 
              "locality": "м. Львів"
            }
          }
        ]
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

