POST /api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/cancellations?acc_token=793615b998564fec946a60f44061b53b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/cancellations/9290af2ff14641cbbd27daab24c4ce5b
{
  "data": {
    "status": "pending", 
    "reason": "cancellation reason", 
    "reasonType": "cancelled", 
    "date": "2017-02-16T11:57:13.938665+02:00", 
    "cancellationOf": "tender", 
    "id": "9290af2ff14641cbbd27daab24c4ce5b"
  }
}

