GET /api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids?acc_token=12edb463846948e88706a2df2912ba45 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids/64c6b855beba4212a4e8434cec225ff3/documents/d647bef6eee54a75adfaf07f87b7fbb1?download=9d8c61714bf04567849c2ca561ee1f0a", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-02-16T13:35:29.551953+02:00", 
          "id": "d647bef6eee54a75adfaf07f87b7fbb1", 
          "dateModified": "2017-02-16T13:35:29.551986+02:00"
        }, 
        {
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "title": "Proposal_top_secrets.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/bids/64c6b855beba4212a4e8434cec225ff3/documents/6a9751a40b364da4aab33472bfc110cd?download=01fc3d85ef00483aa62bba9d86ce8dc9", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-02-16T13:35:29.672007+02:00", 
          "id": "6a9751a40b364da4aab33472bfc110cd", 
          "dateModified": "2017-02-16T13:35:29.672039+02:00"
        }
      ], 
      "id": "64c6b855beba4212a4e8434cec225ff3", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "35e7d4ecdfe2489989257ea9acd43787", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "id": "631df1f78a114db8afb0c09592b20178", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }
  ]
}

