GET /api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/bids?acc_token=793615b998564fec946a60f44061b53b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "status": "active", 
      "documents": [
        {
          "confidentiality": "public", 
          "language": "uk", 
          "title": "Proposal.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/bids/018a3958273a439ba83f5c996cb9525c/documents/2a545ab3d99b40c3ac4f2b5eb16e3eff?download=917e8726d4f941bb9eccc8ce32f2b469", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-02-16T11:57:07.873882+02:00", 
          "id": "2a545ab3d99b40c3ac4f2b5eb16e3eff", 
          "dateModified": "2017-02-16T11:57:07.873914+02:00"
        }, 
        {
          "confidentiality": "buyerOnly", 
          "language": "uk", 
          "title": "Proposal_top_secrets.pdf", 
          "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/bids/018a3958273a439ba83f5c996cb9525c/documents/163b0fbd8cf04677a1e86fd53b14dcb9?download=82ce90cfe71d4579851dbdfb1500f521", 
          "confidentialityRationale": "Only our company sells badgers with pink hair.", 
          "format": "application/pdf", 
          "documentOf": "tender", 
          "datePublished": "2017-02-16T11:57:08.000731+02:00", 
          "id": "163b0fbd8cf04677a1e86fd53b14dcb9", 
          "dateModified": "2017-02-16T11:57:08.000764+02:00"
        }
      ], 
      "id": "018a3958273a439ba83f5c996cb9525c", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ]
    }, 
    {
      "status": "active", 
      "id": "f312a5e0d7824a9782aa853d39357fa5", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }, 
    {
      "status": "unsuccessful", 
      "id": "d7ea82f49c684739b0503f593cd4d21d", 
      "tenderers": [
        {
          "contactPoint": {
            "email": "fake@mail.com", 
            "telephone": "+380 (322) 12-34-56", 
            "name": "Іван Іваненко"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "«Снігур»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 35", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ]
    }
  ]
}

