PATCH /api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/qualifications/8015a4384ef746b2b60bd6340008ce10?acc_token=793615b998564fec946a60f44061b53b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "unsuccessful"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "unsuccessful", 
    "date": "2017-02-16T11:57:10.112655+02:00", 
    "id": "8015a4384ef746b2b60bd6340008ce10", 
    "bidID": "d7ea82f49c684739b0503f593cd4d21d"
  }
}

