PATCH /api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/contracts/30ed55ef482e4cbcaa880765c712e719/documents/1d2f6ac219994d128c045c0d8fbb07ee?acc_token=12edb463846948e88706a2df2912ba45 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "title_en": "Title of Document", 
    "language": "en", 
    "description_en": "Description of Document"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "language": "en", 
    "title": "contract_second_document.doc", 
    "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/contracts/30ed55ef482e4cbcaa880765c712e719/documents/1d2f6ac219994d128c045c0d8fbb07ee?download=2872cffc15a94346a510fc526de48bb9", 
    "format": "application/msword", 
    "title_en": "Title of Document", 
    "description_en": "Description of Document", 
    "datePublished": "2017-02-16T13:35:35.196767+02:00", 
    "documentOf": "tender", 
    "id": "1d2f6ac219994d128c045c0d8fbb07ee", 
    "dateModified": "2017-02-16T13:35:35.196813+02:00"
  }
}

