GET /api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/contracts/09904d4c4f924dc6a38e1a262c3abf7c/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": [
    {
      "language": "uk", 
      "title": "contract_first_document.doc", 
      "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/contracts/09904d4c4f924dc6a38e1a262c3abf7c/documents/6a2b163fe7f142d7b0afc2d1f72e5843?download=7e6f785df32941eab43779936173d40b", 
      "format": "application/msword", 
      "documentOf": "tender", 
      "datePublished": "2017-02-16T11:57:13.026233+02:00", 
      "id": "6a2b163fe7f142d7b0afc2d1f72e5843", 
      "dateModified": "2017-02-16T11:57:13.026275+02:00"
    }
  ]
}

