PATCH /api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d?acc_token=793615b998564fec946a60f44061b53b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2017-02-24T11:57:07.411892+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2017-02-09T11:57:07.199743+02:00", 
      "endDate": "2017-02-09T11:57:08.199743+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-02-09T11:57:07.199743+02:00", 
      "clarificationsUntil": "2017-02-23T11:57:07.411892+02:00", 
      "endDate": "2017-02-23T11:57:07.411892+02:00", 
      "invalidationDate": "2017-02-16T11:57:07.545537+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "operator": "ua", 
    "next_check": "2017-02-24T11:57:07.411892+02:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2017-02-16T11:57:07.086012+02:00", 
        "title": "Калорійність", 
        "date": "2017-02-16T11:57:06.997018+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "81765ea5329145e793ed2baaddbbdbc6", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "5850b6f8866b495ab93c01287a832c5d", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/documents/4d770985b7a841dbb172a79431f88157?download=1274c7f2e36449e9867140b0baf8f3d9", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T11:57:06.668408+02:00", 
        "id": "4d770985b7a841dbb172a79431f88157", 
        "dateModified": "2017-02-16T11:57:06.668444+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/documents/313b15e0c904489e9868c0db73eed310?download=f196407d7fbc4391a2e820cd8f5c30d4", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T11:57:06.773953+02:00", 
        "id": "313b15e0c904489e9868c0db73eed310", 
        "dateModified": "2017-02-16T11:57:06.773986+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/5850b6f8866b495ab93c01287a832c5d/documents/313b15e0c904489e9868c0db73eed310?download=01e68f1be3fc471ba94405a6540111aa", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T11:57:06.773953+02:00", 
        "id": "313b15e0c904489e9868c0db73eed310", 
        "dateModified": "2017-02-16T11:57:06.886734+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "tenderID": "R-UA-2017-02-16-000001", 
    "dateModified": "2017-02-16T11:57:07.550590+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2017-02-09T11:57:07.199743+02:00", 
      "endDate": "2017-02-24T11:57:07.411892+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-02-26T00:00:00+02:00"
    }, 
    "procurementMethodType": "aboveThresholdTS", 
    "date": "2017-02-16T11:57:06.010358+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-08T11:57:03.681359+02:00", 
          "endDate": "2017-04-07T11:57:03.681416+02:00"
        }, 
        "id": "b681beba402b4c5e9cf13db2dec1b70e", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-08T11:57:03.681447+02:00", 
          "endDate": "2017-04-07T11:57:03.681470+02:00"
        }, 
        "id": "5f47716322524940920f071a1df7a2f1", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

