PATCH /api/2.3/tenders/69620e7245b048d696d61d9b5061cee2?acc_token=12edb463846948e88706a2df2912ba45 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 120
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "tenderPeriod": {
      "endDate": "2017-02-24T13:35:29.081121+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "procurementMethod": "open", 
    "complaintPeriod": {
      "startDate": "2017-02-09T13:35:28.866533+02:00", 
      "endDate": "2017-02-09T13:35:29.866533+02:00"
    }, 
    "enquiryPeriod": {
      "startDate": "2017-02-09T13:35:28.866533+02:00", 
      "clarificationsUntil": "2017-02-23T13:35:29.081121+02:00", 
      "endDate": "2017-02-23T13:35:29.081121+02:00", 
      "invalidationDate": "2017-02-16T13:35:29.213728+02:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "operator": "ua", 
    "next_check": "2017-02-24T13:35:29.081121+02:00", 
    "awardCriteria": "lowestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "dateAnswered": "2017-02-16T13:35:28.749826+02:00", 
        "title": "Калорійність", 
        "date": "2017-02-16T13:35:28.651782+02:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "9f81c4879d5748c7a601deb37ed57627", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "title_en": "Services in school canteens", 
    "id": "69620e7245b048d696d61d9b5061cee2", 
    "guarantee": {
      "currency": "USD", 
      "amount": 8.0
    }, 
    "documents": [
      {
        "language": "uk", 
        "title": "Notice.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/documents/6f7cd941e6d64479a88f1404aeb178fb?download=e62c67795ed640ff83fb024d688fca9b", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T13:35:28.315761+02:00", 
        "id": "6f7cd941e6d64479a88f1404aeb178fb", 
        "dateModified": "2017-02-16T13:35:28.315794+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/documents/98f7c328d6c248528f1307046045127a?download=edd57144ff0c426fb38be60f4bb626d8", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T13:35:28.425081+02:00", 
        "id": "98f7c328d6c248528f1307046045127a", 
        "dateModified": "2017-02-16T13:35:28.425114+02:00"
      }, 
      {
        "language": "uk", 
        "title": "AwardCriteria-2.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.3/tenders/69620e7245b048d696d61d9b5061cee2/documents/98f7c328d6c248528f1307046045127a?download=e870c5ad71704344ac8888d1090bedc5", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-02-16T13:35:28.425081+02:00", 
        "id": "98f7c328d6c248528f1307046045127a", 
        "dateModified": "2017-02-16T13:35:28.541864+02:00"
      }
    ], 
    "title": "Послуги шкільних їдалень", 
    "tenderID": "R-UA-2017-02-16-000001", 
    "dateModified": "2017-02-16T13:35:29.218818+02:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2017-02-09T13:35:28.866533+02:00", 
      "endDate": "2017-02-24T13:35:29.081121+02:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-02-26T00:00:00+02:00"
    }, 
    "procurementMethodType": "aboveThresholdTS", 
    "date": "2017-02-16T13:35:27.635873+02:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-08T13:35:25.283623+02:00", 
          "endDate": "2017-04-07T13:35:25.283712+02:00"
        }, 
        "id": "7a806448d0014f8fab19eaf6b328dfeb", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }, 
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Test", 
          "id": "37810000-9"
        }, 
        "description_en": "Services in school canteens", 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "17.21.1", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "deliveryAddress": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "deliveryDate": {
          "startDate": "2017-03-08T13:35:25.283746+02:00", 
          "endDate": "2017-04-07T13:35:25.283773+02:00"
        }, 
        "id": "9462dda6089446b3b7aa7cda61518b33", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 1
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "kind": "general", 
      "name": "ЗОСШ #10 м.Вінниці", 
      "address": {
        "postalCode": "21027", 
        "countryName": "Україна", 
        "streetAddress": "вул. Стахурського. 22", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }, 
      "contactPoint": {
        "url": "http://sch10.edu.vn.ua/", 
        "name_en": "Kutsa Svitlana V.", 
        "name": "Куца Світлана Валентинівна", 
        "availableLanguage": "uk", 
        "telephone": "+380 (432) 46-53-02"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName_en": "The institution \"Secondary school I-III levels № 10 Vinnitsa City Council\"", 
        "id": "21725150", 
        "legalName": "Заклад \"Загальноосвітня школа І-ІІІ ступенів № 10 Вінницької міської ради\""
      }, 
      "name_en": "School #10 of Vinnytsia"
    }
  }
}

